In [1]:
import numpy as np

In [2]:
X = np.array([
    [0, -6],
    [4, 4],
    [0, 0],
    [-5, 2]
])

Zdef = np.array([
    [-5, 2],
    [0, -6]
])

Z = Zdef

def l1(a,b):
    d =  np.abs(a[0]-b[0])+np.abs(a[1]-b[1])
    return d


def assign_l1(X,Z):
    at = np.array( [0] * len(X)) 
    for ix in range(len(X)):
        d = np.array( [0.0] * len(Z) )
        for iz in range(len(Z)):
           d[iz] = np.linalg.norm( [X[ix][0]-Z[iz][0], X[ix][1]-Z[iz][1]] ,ord=1)
           #d[iz] = l1(X[ix], Z[iz])
        #print("d",d)
        #print("argmin",np.argmin(d))
        at[ix] = np.argmin(d);   
    return at

def assign_l2(X,Z):
    a = np.array( [0] * len(X)) 
    for ix in range(len(X)):
        d = np.array( [0] * len(Z) )
        for iz in range(len(Z)):
           d[iz] = np.linalg.norm( [X[ix][0]-Z[iz][0], X[ix][1]-Z[iz][1]] ,ord=2)
        a[ix] = np.argmin(d);   
    return a

#for i in range(100):
#    a = assign_l1(X,Z)
#    print(a)

def get_one_z_k_menoids_l1(C,XS):
    #print("C",C)
    #print("XS",XS)
    costs = np.array( [0] * len(XS)) 
    for ix in range(len(XS)):
        for ic in range(len(C)):
           costs[ix] += np.linalg.norm( [XS[ix][0]-C[ic][0], XS[ix][1]-C[ic][1]] ,ord=1)
    iz = np.argmin(costs)       
    return(iz);   


def get_z_k_menoids_l1(a):
    Z1 = np.zeros(Z.shape)
    for k in range(2):
        xk = X[np.where(a == k)]
        Z1[k] = X[get_one_z_k_menoids_l1(xk,X)]
    return Z1


def get_one_z_k_menoids_l2(C,XS):
    #print("C",C)
    #print("XS",XS)
    costs = np.array( [0] * len(XS)) 
    for ix in range(len(XS)):
        for ic in range(len(C)):
           costs[ix] += np.linalg.norm( [XS[ix][0]-C[ic][0], XS[ix][1]-C[ic][1]] ,ord=2)
    iz = np.argmin(costs)       
    return(iz);   


def get_z_k_menoids_l2(a):
    Z1 = np.zeros(Z.shape)
    for k in range(2):
        xk = X[np.where(a == k)]
        Z1[k] = X[get_one_z_k_menoids_l2(xk,X)]
    return Z1


def get_z_k_means_l1(a):
    Z1 = np.zeros(Z.shape)
    for k in range(2):
        xk = X[np.where(a == k)]
        Z1[k] = np.array([np.median(xk[:,0]),np.median(xk[:,1])])
    return Z1




print("## K-medoids algorithm with  l1  norm.")
for i in range(100):
    a = assign_l1(X,Z)
    Z = get_z_k_menoids_l1(a)
print("====>Z")
print(Z)
print("====>Assignment")
for k in range(2):
    xk = X[np.where(a == k)]
    print(xk)

print("## K-medoids algorithm with  l2  norm.")
Z = Zdef
for i in range(100):
    a = assign_l2(X,Z)
    Z = get_z_k_menoids_l2(a)
print("====>Z")
print(Z)
print("====>Assignment")
for k in range(2):
    xk = X[np.where(a == k)]
    print(xk)


print("################################à")
print("## K-means algorithm with  l1  norm.")
Z = Zdef
for i in range(100):
    a = assign_l1(X,Z)
    Z = get_z_k_means_l1(a)
print("====>Z")
print(Z)
print("====>Assignment")
for k in range(2):
    xk = X[np.where(a == k)]
    print(xk)




## K-medoids algorithm with  l1  norm.
====>Z
[[ 4.  4.]
 [ 0. -6.]]
====>Assignment
[[ 4  4]
 [-5  2]]
[[ 0 -6]
 [ 0  0]]
## K-medoids algorithm with  l2  norm.
====>Z
[[ 0.  0.]
 [ 0. -6.]]
====>Assignment
[[ 4  4]
 [ 0  0]
 [-5  2]]
[[ 0 -6]]
################################à
## K-means algorithm with  l1  norm.
====>Z
[[-0.5  3. ]
 [ 0.  -3. ]]
====>Assignment
[[ 4  4]
 [-5  2]]
[[ 0 -6]
 [ 0  0]]
